baseURL = 'https://lemon.software/'
languageCode = 'en-us'
title = 'lemon'
theme = "hugo-toigian"

[params]
toc = true
comments = true

[params.author]
name = "Sayan Mallick"
email = "sayan@sent.com"


[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
noClasses = false
tabWidth = 4
[markup.tableOfContents]
startLevel = 2
endLevel = 4
ordered = true

[menu]
[[menu.nav]]
name = "Contact"
url = "/contact"
weight = 2

[[menu.nav]]
name = "Posts"
url = "/posts"
weight = 3
